version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      assignees:
          - 'BakirGracic'
      commit-message:
          prefix: 'dependabot npm update: '
      labels:
          - 'dependabot-npm-update'
