import '@/css/tailwind.css';
import { InterFont, RobotoMonoFont } from '@/lib/font';
import { type Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Clean template for new NextJS projects',
	description: 'Generated by create next app and with template github.com/BakirGracic/nextjs-clean-template',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html>
			<body className={`${InterFont.variable} ${RobotoMonoFont.variable}`}>{children}</body>
		</html>
	);
}
